### ISSUE TITLE
Merge in lost Mahjongg cardsets?

### ISSUE THREAD

**Issue by joeraz** [shlomif/PySolFC-Cardsets#13]
I'm wondering if there's a reason the extra Mahjongg cardsets at https://github.com/shlomif/PySol-Extra-Mahjongg-Cardsets have not been merged into the main cardsets repo?

**Comment by shlomif** [comment]
On Fri, 19 May 2023 18:13:20 -0700
"Joe R." ***@***.***> wrote:

> I'm wondering if there's a reason the extra Mahjongg cardsets at
> https://github.com/shlomif/PySol-Extra-Mahjongg-Cardsets have not been merged
> into the main cardsets repo?
> 

the licence is GPLv2-only insteadof gpl version 2-and-above.

-- 

Shlomi Fish       https://www.shlomifish.org/
“So, who the hell is Qoheleth?” - https://shlom.in/qoheleth

Chuck Norris has 50 years of proven experience in PHP/MySQL/Java. Each.
    — https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by joeraz** [comment]
> On Fri, 19 May 2023 18:13:20 -0700 "Joe R." ***@***.***> wrote: I'm wondering if there's a reason the extra Mahjongg cardsets at https://github.com/shlomif/PySol-Extra-Mahjongg-Cardsets have not been merged into the main cardsets repo?
> the licence is GPLv2-only insteadof gpl version 2-and-above.
> […](#)
> -- Shlomi Fish https://www.shlomifish.org/ “So, who the hell is Qoheleth?” - https://shlom.in/qoheleth Chuck Norris has 50 years of proven experience in PHP/MySQL/Java. Each. — https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/ Please reply to list if it's a mailing list post - https://shlom.in/reply .

Are you sure about that?

The COPYRIGHT files on the individual cardsets in that repo say they can be used with later versions of the GPL, and they match T. Kirk's other cardsets currently in the main cardsets repo.

**Comment by shlomif** [comment]
On Sat, 20 May 2023 07:00:01 -0700
"Joe R." ***@***.***> wrote:

> > On Fri, 19 May 2023 18:13:20 -0700 "Joe R." ***@***.***> wrote: I'm
> > wondering if there's a reason the extra Mahjongg cardsets at
> > https://github.com/shlomif/PySol-Extra-Mahjongg-Cardsets have not been
> > merged into the main cardsets repo? the licence is GPLv2-only insteadof gpl
> > version 2-and-above. […](#) -- Shlomi Fish https://www.shlomifish.org/ “So,
> > who the hell is Qoheleth?” - https://shlom.in/qoheleth Chuck Norris has 50
> > years of proven experience in PHP/MySQL/Java. Each. —
> > https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/ Please reply to
> > list if it's a mailing list post - https://shlom.in/reply .  
> 
> Are you sure about that?
> 
> The COPYRIGHT files on the individual cardsets in that repo say they can be
> used with later versions of the GPL, and they match T. Kirk's other cardsets
> currently in the main cardsets repo.
> 

no -  i'm not sure

-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/humour/bits/facts/Emma-Watson/

Larry Wall can understand the Perl code he wrote last year.
    — https://www.shlomifish.org/humour/bits/facts/Larry-Wall/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by joeraz** [comment]
So comparing the COPYRIGHT files on the individual cardsets a little more closely, it looks to me like they are under the same license as cardsets currently in the main repo (Compare https://github.com/shlomif/PySol-Extra-Mahjongg-Cardsets/blob/master/Lost-Mahjongg-Cardsets/cardset-Beige%20Fantastic%20Mahjongg/COPYRIGHT to  https://github.com/shlomif/PySolFC-Cardsets/blob/master/cardset-1567/COPYRIGHT) and it sounds like they can be used with later versions of the GPL.  A lot of these cardsets were created by the same person (T. Kirk), and I've identified a few other lost cardsets from them as well (and know about the existence of a few others I'm trying to track down).

If there is an issue with these cardsets, that might mean that some cardsets currently in the main repo are not GPLv3-compatible either, in which case, tons of cardsets might need to be purged before the next release.

**Comment by shlomif** [comment]
On Thu, 25 May 2023 15:22:19 -0700
"Joe R." ***@***.***> wrote:

> So comparing the COPYRIGHT files on the individual cardsets a little more
> closely, it looks to me like they are under the same license as cardsets
> currently in the main repo (Compare
> https://github.com/shlomif/PySol-Extra-Mahjongg-Cardsets/blob/master/Lost-Mahjongg-Cardsets/cardset-Beige%20Fantastic%20Mahjongg/COPYRIGHT
> to
> https://github.com/shlomif/PySolFC-Cardsets/blob/master/cardset-1567/COPYRIGHT)
> and it sounds like they can be used with later versions of the GPL.  A lot of
> these cardsets were created by the same person (T. Kirk), and I've identified
> a few other lost cardsets from them as well (and know about the existence of
> a few others I'm trying to track down).
> 
> If there is an issue with these cardsets, that might mean that some cardsets
> currently in the main repo are not GPLv3-compatible either, in which case,
> tons of cardsets might need to be purged before the next release.
> 

I understand. IANAL, but I think a GPLed program can load and manipulate
non-gpl-compatible data. E.g: gnu emacs or gnu nano can be used to edit
proprietary source code. 


-- 

Shlomi Fish       https://www.shlomifish.org/
Why I Love Perl - https://shlom.in/joy-of-perl

God ties Chuck Norris’ camel.
    — https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by joeraz** [comment]
That is true - I think of GPL projects like ScummVM that pretty much need proprietary data files to run, and sometimes even get included as part of commercial releases of said files.

So based on what we're saying, it sounds like we should be able to merge the cardsets packages without a licensing conflict.

**Comment by joeraz** [comment]
I'll do this merge as part of the updates discussed in issue #14

While doing this merge, I'll make sure to double-check the license files on each of them to be extra sure there aren't any conflicts.

**Comment by joeraz** [comment]
I've confirmed the licenses and merged what I could.
