### ISSUE TITLE
F1.4Release ffmpeg consideration

### ISSUE THREAD

**Issue by scottfurry** [shlomif/PySolFC-Cardsets#2]
Ran into build problems w/ ffmpeg/qtwebengine being the road block.
Following diff seems prudent and may help > Qt 5.12.4 | future implementation.
I implemented this locally. Gist is to define minimum ffmpeg-# version (using just ffmpeg pulls in early 3.* series and creates clashes in emerge). I used 3.4.5 (last stable before 4.* series).

```diff
diff --git a/dev-qt/qtwebengine/qtwebengine-5.12.3.ebuild b/dev-qt/qtwebengine/qtwebengine-5.12.3.ebuild
index 2c7be01..342aab2 100644
--- a/dev-qt/qtwebengine/qtwebengine-5.12.3.ebuild
+++ b/dev-qt/qtwebengine/qtwebengine-5.12.3.ebuild
@@ -61,7 +61,7 @@ RDEPEND="
        designer? ( ~dev-qt/designer-${PV} )
        geolocation? ( ~dev-qt/qtpositioning-${PV} )
        pulseaudio? ( media-sound/pulseaudio:= )
-       system-ffmpeg? ( media-video/ffmpeg:0= )
+       system-ffmpeg? ( >=media-video/ffmpeg-3.4.5:0= )
        system-icu? ( >=dev-libs/icu-60.2:= )
        widgets? (
                ~dev-qt/qtdeclarative-${PV}[widgets]
```

Hope this helps.

**Comment by shlomif** [comment]
Hi @scottfurry ! I do not understand what this has to do with PySolFC-Cardsets.

**Comment by scottfurry** [comment]
Absolutely nothing. It suppose to go to someone else. Been too long of a day w/ major overhaul/upgrade of software and I posted to the wrong open tab. I'll be fine. Sleep or medication. Apologies for the noise.

**Comment by scottfurry** [comment]
Where's the delete button...
